[project]
name = "pipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "glassflow>=2.0.6",
    "langchain>=0.3.9",
    "openai>=1.55.3",
    "opencv-python>=4.10.0.84",
    "pydantic>=2.10.2",
]
