financial_task:
  description: >
    You are provided with the data on the crops grown by your buisness and the yields for the current quarter as well as employee efficiency reports.
    Using your skills of financial analysis to make decisions on the next quarter and use your current information to build up financial decisions that you would make
    to help your organisation gain better yields.
  expected_output: >
    A list with 10 bullet points that depict the financial decisions that should be taken for the next quarter.
  agent: financial_analyst

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

data_task:
  description: >
    Collect all the necessary data regarding the buisness by acessing the buisness database and also access the web to collect data needed for future financial and agriculture forecasting,
    Your target is to gather information that would be used by the financial_analyst to determine and plan financial decisions for next quarter, and to gather information necessary for 
    reporting analyst to build up a final report that would be presented to the stakeholders.
    You are provided with list of crops grown: {crop_list}, buisness user id: {buisness_id}, plantation id: {plantation_id} and current date: {current_date}.
    When searching through the database make sure that the data are related to the buisness and not to anyone else. make sure to not include data that are unrelated to your buisness.
    you are allowed to query through the gardeners under the plantation buisness, you should not access info of unrelated gardeners.
  expected_output: >
    data on the crops grown by your buisness and the yields for the current quarter as well as employee efficiency reports.
  agent: data_engineer